services:
  - type: web
    name: lstm-webhook-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_server:app --host 0.0.0.0 --port 8000
    autoDeploy: true
