services:
  - type: web
    name: lstm-webhook-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_server:app --host 0.0.0.0 --port 8080
    autoDeploy: true
